A/urls.py
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('posts.urls', namespace='posts')),
    path('account/', include('account.urls', namespace='account')),
]

account/urls.py
from django.urls import path
from . import views


app_name = 'account'
urlpatterns = [
	path('login/', views.user_login, name='login'),
	path('register/', views.user_register, name='register'),
	path('logout/', views.user_logout, name='logout'),
	path('dashboard/<int:user_id>/', views.user_dashboard, name='dashboard'),
	path('edit_profile/<int:user_id>/', views.edit_profile, name='edit_profile'),
	path('phone_login/', views.phone_login, name='phone_login'),
	path('verify/<str:phone>/<int:rand_num>/', views.verify, name='verify'),
	path('follow/', views.follow, name='follow'),
	path('unfollow/', views.unfollow, name='unfollow'),
]

posts/urls.py
from django.urls import path
from . import views


app_name = 'posts'
urlpatterns = [
	path('', views.all_posts, name='all_posts'),
	path('<int:year>-<int:month>-<int:day>-<slug:slug>/', views.post_detail, name='post_detail'),
	path('add_post/<int:user_id>/', views.add_post, name='add_post'),
	path('post_delete/<int:user_id>/<int:post_id>/', views.post_delete, name='post_delete'),
	path('post_edit/<int:user_id>/<int:post_id>/', views.post_edit, name='post_edit'),
	path('add_reply/<int:post_id>/<int:comment_id>/', views.add_reply, name='add_reply'),
	path('like/<int:post_id>/', views.post_like, name='post_like'),
]

posts/models.py
from django.db import models
from django.contrib.auth.models import User
from django.urls import reverse


class Post(models.Model):
	user = models.ForeignKey(User, on_delete=models.CASCADE)
	body = models.TextField(max_length=500)
	slug = models.SlugField(max_length=200)
	created = models.DateTimeField(auto_now_add=True)

	def __str__(self):
		return f'{self.user} - {self.body[:30]}'

	def get_absolute_url(self):
		return reverse('posts:post_detail', args=[self.created.year, self.created.month, self.created.day, self.slug])

	def likes_count(self):
		return self.pvote.count()

	def user_can_like(self, user):
		user_like = user.uvote.all()
		qs = user_like.filter(post=self)
		if qs.exists():
			return True
		return False


class Comment(models.Model):
	user = models.ForeignKey(User, on_delete=models.CASCADE, related_name='ucomment')
	post = models.ForeignKey(Post, on_delete=models.CASCADE, related_name='pcomment')
	reply = models.ForeignKey('self', on_delete=models.CASCADE, null=True, blank=True, related_name='rcomment')
	is_reply = models.BooleanField(default=False)
	body = models.TextField(max_length=400)
	created = models.DateTimeField(auto_now_add=True)

	def __str__(self):
		return f'{self.user} - {self.body[:30]}'

	class Meta:
		ordering = ('-created',)

class Vote(models.Model):
	post = models.ForeignKey(Post, on_delete=models.CASCADE, related_name='pvote')
	user = models.ForeignKey(User, on_delete=models.CASCADE, related_name='uvote')

	def __str__(self):
		return f'{self.user} liked {self.post}'

posts/forms.py
from django import forms
from .models import Post, Comment


class AddPostForm(forms.ModelForm):
	class Meta:
		model = Post
		fields = ('body',)


class EditPostForm(forms.ModelForm):
	class Meta:
		model = Post
		fields = ('body',)


class AddCommentForm(forms.ModelForm):
	class Meta:
		model = Comment
		fields = ('body',)
		widgets = {
			'body': forms.Textarea(attrs={'class':'form-control'})
		}
		error_messages = {
			'body':{
				'required': 'این فیلد اجباری است',
			}
		}
		help_texts = {
			'body':'max 400 char'
		}

class AddReplyForm(forms.ModelForm):
	class Meta:
		model = Comment
		fields = ('body',)

posts/views.py
from django.shortcuts import render, get_object_or_404, redirect
from .models import Post, Comment, Vote
from .forms import AddPostForm, EditPostForm, AddCommentForm, AddReplyForm
from django.contrib import messages
from django.utils.text import slugify
from django.contrib.auth.decorators import login_required
import redis
from django.conf import settings



def all_posts(request):
	posts = Post.objects.all()
	return render(request, 'posts/all_posts.html', {'posts':posts})

redis_con = redis.Redis(settings.REDIS_HOST, settings.REDIS_PORT, settings.REDIS_DB)
def post_detail(request, year, month, day, slug):
	post = get_object_or_404(Post, created__year=year, created__month=month, created__day=day, slug=slug)
	comments = Comment.objects.filter(post=post, is_reply=False)
	reply_form = AddReplyForm()
	redis_con.hsetnx('post_views', post.id, 0)
	rviews = redis_con.hincrby('post_views', post.id)
	can_like = False
	if request.user.is_authenticated:
		if post.user_can_like(request.user):
			can_like = True
	if request.method == 'POST':
		form = AddCommentForm(request.POST)
		if form.is_valid():
			new_comment = form.save(commit=False)
			new_comment.post = post
			new_comment.user = request.user
			new_comment.save()
			messages.success(request, 'you comment submitted successfully')
	else:
		form = AddCommentForm()
	return render(request, 'posts/post_detail.html', {'post':post, 'comments':comments, 'form':form, 'reply':reply_form, 'can_like':can_like, 'rviews':rviews})

@login_required
def add_post(request, user_id):
	if request.user.id == user_id:
		if request.method == 'POST':
			form = AddPostForm(request.POST)
			if form.is_valid():
				new_post = form.save(commit=False)
				new_post.user = request.user
				new_post.slug = slugify(form.cleaned_data['body'][:30])
				new_post.save()
				messages.success(request, 'your post submitted', 'success')
				return redirect('account:dashboard', user_id)
		else:
			form = AddPostForm()
		return render(request, 'posts/add_post.html', {'form':form})
	else:
		return redirect('posts:all_posts')

@login_required
def post_delete(request, user_id, post_id):
	if user_id == request.user.id:
		Post.objects.filter(pk=post_id).delete()
		messages.success(request, 'your post deleted successfully', 'success')
		return redirect('account:dashboard', user_id)
	else:
		return redirect('posts:all_posts')

@login_required
def post_edit(request, user_id, post_id):
	if request.user.id == user_id:
		post = get_object_or_404(Post, pk=post_id)
		if request.method == 'POST':
			form = EditPostForm(request.POST, instance=post)
			if form.is_valid():
				ep = form.save(commit=False)
				ep.slug = slugify(form.cleaned_data['body'][:30])
				ep.save()
				messages.success(request, 'your post edited successfully', 'success')
				return redirect('account:dashboard', user_id)
		else:
			form = EditPostForm(instance=post)
		return render(request, 'posts/edit_post.html', {'form':form})
	else:
		return redirect('posts:all_posts')


@login_required
def add_reply(request, post_id, comment_id):
	post = get_object_or_404(Post, id=post_id)
	comment = get_object_or_404(Comment, pk=comment_id)
	if request.method == 'POST':
		form = AddReplyForm(request.POST)
		if form.is_valid():
			reply = form.save(commit=False)
			reply.user = request.user
			reply.post = post
			reply.reply = comment
			reply.is_reply = True
			reply.save()
			messages.success(request, 'your reply submitted successfully', 'success')
	return redirect('posts:post_detail', post.created.year, post.created.month, post.created.day, post.slug)


@login_required
def post_like(request, post_id):
	post = get_object_or_404(Post, id=post_id)
	like = Vote(post=post, user=request.user)
	like.save()
	messages.success(request, 'you liked successfully', 'success')
	return redirect('posts:post_detail', post.created.year, post.created.month, post.created.day, post.slug)

posts/templates/posts/add_post.html
{% extends 'base.html' %}

{% block title %} {{ request.user.username }} add post {% endblock %}

{% block content %}
    <form action="" method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <input type="submit" value="Add Post" class="btn btn-primary">
    </form>
{% endblock %}

posts/templates/posts/all_posts.html
{% extends 'base.html' %}

{% block title %} Home {% endblock %}

{% block content %}
    {% for post in posts %}
        <div class="card">
            <p class="card-header"><a href="{% url 'account:dashboard' post.user.id %}">{{ post.user }}</a></p>
            <p class="card-body"><a href="{{ post.get_absolute_url }}">{{ post.body }}</a></p>
        </div><br/>
    {% endfor %}
{% endblock %}

posts/templates/posts/edit_post.html
{% extends 'base.html' %}

{% block title %} Edit Post {% endblock %}

{% block content %}
    <form action="" method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <input type="submit" value="Edit" class="btn btn-primary">
    </form>
{% endblock %}

posts/templates/posts/post_detail.html
{% extends 'base.html' %}

{% block content %}
    {% if request.user.is_authenticated and request.user.id == post.user.id%}
        <a href="{% url 'posts:post_delete' post.user.id post.id %}">delete post</a>
        <a href="{% url 'posts:post_edit' post.user.id post.id %}">Edit post</a>
    {% endif %}
    <p>{{ post.user }} | {{ post.created|date }} | {{ rviews }} views</p>
    <p>{{ post.body }}</p><hr/>

    {% with total=comments.count %}
        <p>This post has {{ total }} comment{{ total|pluralize }}</p>
    {% endwith %}

    {% if request.user.is_authenticated %}
        <a href="{% url 'posts:post_like' post.id %}" class="btn btn-primary {% if can_like %}disabled {% endif %} col-md-2">Like {{ post.likes_count }}</a>
    {% endif %}
<br/><br/><br/>

    {% if request.user.is_authenticated %}
    <form action="" method="post" novalidate class="col-md-6">
        {% csrf_token %}
        {{ form.as_p }}
        <input type="submit" value="Send" class="btn btn-primary">
    </form>
    {% else %}
        <p>only logged in users can send comments</p>
    {% endif %}<br/><br/><br/>

    {% for comment in comments %}
        <div class="card bg-dark text-white">
            <p class="card-header">{{ comment.user }} <a href="">reply</a></p>
            <p class="card-body">{{ comment.body }}</p>
            {% if request.user.is_authenticated %}
            <div class="card-body" style="display:none">
                <form action="{% url 'posts:add_reply' post.id comment.id %}" method="post">
                    {% csrf_token %}
                    {{ reply.as_p }}
                    <input type="submit" value="Send">
                </form>
            </div>
            {% else %}
                <p>you have to login to send reply</p>
            {% endif %}
            {% for reply in comment.rcomment.all %}
                <p class="bg-primary text-white p-3 m-5">{{ reply.user }} <br/> {{ reply.body }}</p>
            {% endfor %}
        </div><br/>
    {% empty %}
        <p>There is no comment</p>
    {% endfor %}
{% endblock %}